discordBot.clientId=
discordBot.clientSecret=
discordBot.callbackUrl=
discordBot.token=

server.baseURL=
server.port=
server.servlet.session.cookie.name=
server.servlet.session.cookie.same-site=
server.servlet.session.cookie.http-only=
server.servlet.session.cookie.secure=
server.servlet.session.timeout=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=
spring.jpa.generate-dll=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.dialect=